In [4]:
import pandas as pd
import numpy as np

In [57]:
people={'first':['corey','jane','joe','chris',np.nan,None,'NA'],
       'last':['Schafer','Doe','Doe','Schafer',np.nan,np.nan,'Missing'],
        'email':['corey@email.com','jane@email.com','joe@email.com',None,np.nan,'anonymous@email.com','NA'],
         'age':['33','53','63','36',None,None,'Missing']}

In [58]:
df = pd.DataFrame(people)
df.replace('NA',np.nan,inplace=True)
df.replace('Missing',np.nan,inplace=True)

In [62]:
df

   first     last                email   age
0  corey  Schafer      corey@email.com    33
1   jane      Doe       jane@email.com    53
2    joe      Doe        joe@email.com    63
3  chris  Schafer                 None    36
4    NaN      NaN                  NaN  None
5   None      NaN  anonymous@email.com  None
6    NaN      NaN                  NaN   NaN

In [60]:
df.dropna()

   first     last            email age
0  corey  Schafer  corey@email.com  33
1   jane      Doe   jane@email.com  53
2    joe      Doe    joe@email.com  63

In [61]:
df.dropna(axis='index',how='all',subset=['last','email'])

   first     last                email   age
0  corey  Schafer      corey@email.com    33
1   jane      Doe       jane@email.com    53
2    joe      Doe        joe@email.com    63
3  chris  Schafer                 None    36
5   None      NaN  anonymous@email.com  None

In [44]:
df.dropna(axis='index', how='all')  #has  to be  all

   first     last            email age
0  corey  Schafer  corey@email.com  33
1   jane      Doe   jane@email.com  53
2    joe      Doe    joe@email.com  63
3  chris  Schafer             None  36

In [63]:
df.isna()

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False   True  False
4   True   True   True   True
5   True   True  False   True
6   True   True   True   True

In [54]:
df.isna()

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False   True  False
4   True   True   True  False
5   True   True   True   True
6   True   True   True   True

In [64]:
df.fillna(0)

   first     last                email age
0  corey  Schafer      corey@email.com  33
1   jane      Doe       jane@email.com  53
2    joe      Doe        joe@email.com  63
3  chris  Schafer                    0  36
4      0        0                    0   0
5      0        0  anonymous@email.com   0
6      0        0                    0   0

In [65]:
df.dtypes

first    object
last     object
email    object
age      object
dtype: object

In [66]:
df['age'].mean()

TypeError: can only concatenate str (not "int") to str

In [67]:
df['age']=df['age'].astype(float)

In [69]:
df['age'].mean()

np.float64(46.25)