In [1]:
import pandas  as pd
import numpy as  np

In [7]:
filename='pandas/developer.csv'

In [8]:
df = pd.read_csv(filename)

In [4]:
df.head(100)

,respondent_id,survey_year,country,age,gender,education_level,years_of_experience,role,employment_status,company_size,...,ai_usage_frequency,ai_productivity_boost_pct,ai_sentiment,ai_job_threat_perception,primary_learning_source,open_source_contributor,looking_for_job,remote_work_preference_1to5,burnout_frequency,want_to_learn_next
0,R00001,2024,India,43,Man,Some college,22,Front-End Developer,Unemployed,1-10,...,Weekly,14,Somewhat positive,Minimal threat,Online courses,1,Actively looking,2,Sometimes,Elixir;Zig;AI/ML
1,R00002,2025,Italy,28,Man,Master's degree,7,Machine Learning Engineer,Unemployed,201-1000,...,Weekly,8,Somewhat positive,Minimal threat,Stack Overflow,1,Not looking,4,Often,Kubernetes;Elixir;Go
2,R00003,2021,South Africa,23,Woman,Master's degree,0,Machine Learning Engineer,Full-time,1001-5000,...,Rarely,1,Very negative,Significant threat,YouTube,0,Open to offers,5,Often,Go
3,R00004,2023,India,22,Prefer not to say,Bachelor's degree,1,QA / Test Engineer,Unemployed,10000+,...,Multiple times daily,61,Neutral,Minimal threat,Stack Overflow,1,Open to offers,3,Rarely,HTMX;Swift;Rust
4,R00005,2025,United States,34,Man,Bachelor's degree,11,Front-End Developer,Full-time,51-200,...,Weekly,15,Neutral,Moderate threat,Official docs,0,Open to offers,1,Sometimes,TypeScript
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,R00096,2020,Brazil,28,Man,Bachelor's degree,7,Data Scientist,Freelance,1-10,...,Multiple times daily,56,Somewhat positive,Moderate threat,Official docs,1,Not looking,4,Sometimes,Python;Rust;Zig
96,R00097,2023,United States,50,Man,Bachelor's degree,30,Front-End Developer,Full-time,201-1000,...,Weekly,26,Very negative,No threat,YouTube,0,Not looking,5,Always,TypeScript;Rust
97,R00098,2024,India,52,Man,Self-taught / Bootcamp,28,Back-End Developer,Full-time,5001-10000,...,Multiple times daily,27,Very positive,Minimal threat,Books,0,Not looking,4,Rarely,Python;Swift;Rust
98,R00099,2025,Canada,34,Man,Bachelor's degree,14,Back-End Developer,Full-time,1001-5000,...,Rarely,4,Very negative,No threat,ChatGPT/AI,0,Open to offers,5,Sometimes,Zig
99,R00100,2020,Japan,30,Man,Bachelor's degree,14,Full-Stack Developer,Freelance,1-10,...,Weekly,13,Somewhat positive,Minimal threat,Colleagues,1,Open to offers,4,Sometimes,Go

In [16]:
us_filter=(df['country']=='United States') & (df['languages_used'].str.contains('Python'))

In [17]:
df.loc[us_filter, ['country','employment_status','languages_used','annual_salary_usd']]

,country,employment_status,languages_used,annual_salary_usd
11,United States,Full-time,SQL;Go;Python;JavaScript,211500
40,United States,Full-time,Python;Dart;Go;HTML/CSS,37200
49,United States,Student,Python;JavaScript;C#;HTML/CSS;Swift,19840
108,United States,Part-time,Bash/Shell;Python;C#;Go;Rust;Kotlin,221900
109,United States,Unemployed,Elixir;JavaScript;Python,0
...,...,...,...,...
11930,United States,Part-time,C;SQL;Python;C++;Java;HTML/CSS,110200
11939,United States,Full-time,Swift;Python;Zig,23600
11962,United States,Full-time,Python;Bash/Shell;HTML/CSS,46400
11970,United States,Full-time,Python;TypeScript;JavaScript;Go,158900
11984,United States,Full-time,JavaScript;SQL;Python,155700

In [18]:
us_df=df.loc[us_filter, ['country','employment_status','languages_used','annual_salary_usd']]

In [19]:
us_df.head(100)

,country,employment_status,languages_used,annual_salary_usd
11,United States,Full-time,SQL;Go;Python;JavaScript,211500
40,United States,Full-time,Python;Dart;Go;HTML/CSS,37200
49,United States,Student,Python;JavaScript;C#;HTML/CSS;Swift,19840
108,United States,Part-time,Bash/Shell;Python;C#;Go;Rust;Kotlin,221900
109,United States,Unemployed,Elixir;JavaScript;Python,0
...,...,...,...,...
1680,United States,Full-time,Go;SQL;Python;C#;Bash/Shell;Kotlin,86000
1687,United States,Full-time,JavaScript;TypeScript;Python;HTML/CSS,187800
1693,United States,Full-time,SQL;TypeScript;C#;HTML/CSS;Python;JavaScript,90700
1694,United States,Full-time,C;SQL;JavaScript;Python;C#,181600
1695,United States,Full-time,Java;C++;Python,77400

In [11]:
us_df.groupby(['employment_status','languages_used'])['annual_salary_usd'].describe()

                                                                  count  \
employment_status languages_used
Freelance         Bash/Shell                                        2.0
                  Bash/Shell;HTML/CSS                               1.0
                  Bash/Shell;Haskell;TypeScript;Java                1.0
                  Bash/Shell;PHP;SQL;JavaScript                     1.0
                  Bash/Shell;Python;Java                            1.0
...                                                                 ...
Unemployed        SQL;Python;TypeScript;HTML/CSS;Dart;JavaScript    1.0
                  Swift                                             1.0
                  Swift;TypeScript;PHP                              1.0
                  TypeScript;Bash/Shell;Swift;Elixir;C#             1.0
                  TypeScript;JavaScript;Bash/Shell                  1.0

                                                                      mean  \
employment_status languages_used
Freelance         Bash/Shell                                       88450.0
                  Bash/Shell;HTML/CSS                              44600.0
                  Bash/Shell;Haskell;TypeScript;Java              163900.0
                  Bash/Shell;PHP;SQL;JavaScript                    77100.0
                  Bash/Shell;Python;Java                          147700.0
...                                                                    ...
Unemployed        SQL;Python;TypeScript;HTML/CSS;Dart;JavaScript       0.0
                  Swift                                            58660.0
                  Swift;TypeScript;PHP                             33960.0
                  TypeScript;Bash/Shell;Swift;Elixir;C#            32460.0
                  TypeScript;JavaScript;Bash/Shell                     0.0

                                                                           std  \
employment_status languages_used
Freelance         Bash/Shell                                      84357.838996
                  Bash/Shell;HTML/CSS                                      NaN
                  Bash/Shell;Haskell;TypeScript;Java                       NaN
                  Bash/Shell;PHP;SQL;JavaScript                            NaN
                  Bash/Shell;Python;Java                                   NaN
...                                                                        ...
Unemployed        SQL;Python;TypeScript;HTML/CSS;Dart;JavaScript           NaN
                  Swift                                                    NaN
                  Swift;TypeScript;PHP                                     NaN
                  TypeScript;Bash/Shell;Swift;Elixir;C#                    NaN
                  TypeScript;JavaScript;Bash/Shell                         NaN

                                                                       min  \
employment_status languages_used
Freelance         Bash/Shell                                       28800.0
                  Bash/Shell;HTML/CSS                              44600.0
                  Bash/Shell;Haskell;TypeScript;Java              163900.0
                  Bash/Shell;PHP;SQL;JavaScript                    77100.0
                  Bash/Shell;Python;Java                          147700.0
...                                                                    ...
Unemployed        SQL;Python;TypeScript;HTML/CSS;Dart;JavaScript       0.0
                  Swift                                            58660.0
                  Swift;TypeScript;PHP                             33960.0
                  TypeScript;Bash/Shell;Swift;Elixir;C#            32460.0
                  TypeScript;JavaScript;Bash/Shell                     0.0

                                                                       25%  \
employment_status languages_used
Freelance         Bash/Shell                                       58625.0
                  Bash/Shell;HTML/CSS                              44600.0
                  Bash/Shell;Haskell;TypeScript;Java              163900.0
                  Bash/Shell;PHP;SQL;JavaScript                    77100.0
                  Bash/Shell;Python;Java                          147700.0
...                                                                    ...
Unemployed        SQL;Python;TypeScript;HTML/CSS;Dart;JavaScript       0.0
                  Swift                                            58660.0
                  Swift;TypeScript;PHP                             33960.0
                  TypeScript;Bash/Shell;Swift;Elixir;C#            32460.0
                  TypeScript;JavaScript;Bash/Shell                     0.0

                                                                       50%  \
employment_status languages_used
Freelance         Bash/Shell                                       88450.0
                  Bash/Shell;HTML/CSS                              44600.0
                  Bash/Shell;Haskell;TypeScript;Java              163900.0
                  Bash/Shell;PHP;SQL;JavaScript                    77100.0
                  Bash/Shell;Python;Java                          147700.0
...                                                                    ...
Unemployed        SQL;Python;TypeScript;HTML/CSS;Dart;JavaScript       0.0
                  Swift                                            58660.0
                  Swift;TypeScript;PHP                             33960.0
                  TypeScript;Bash/Shell;Swift;Elixir;C#            32460.0
                  TypeScript;JavaScript;Bash/Shell                     0.0

                                                                       75%  \
employment_status languages_used
Freelance         Bash/Shell                                      118275.0
                  Bash/Shell;HTML/CSS                              44600.0
                  Bash/Shell;Haskell;TypeScript;Java              163900.0
                  Bash/Shell;PHP;SQL;JavaScript                    77100.0
                  Bash/Shell;Python;Java                          147700.0
...                                                                    ...
Unemployed        SQL;Python;TypeScript;HTML/CSS;Dart;JavaScript       0.0
                  Swift                                            58660.0
                  Swift;TypeScript;PHP                             33960.0
                  TypeScript;Bash/Shell;Swift;Elixir;C#            32460.0
                  TypeScript;JavaScript;Bash/Shell                     0.0

                                                                       max
employment_status languages_used
Freelance         Bash/Shell                                      148100.0
                  Bash/Shell;HTML/CSS                              44600.0
                  Bash/Shell;Haskell;TypeScript;Java              163900.0
                  Bash/Shell;PHP;SQL;JavaScript                    77100.0
                  Bash/Shell;Python;Java                          147700.0
...                                                                    ...
Unemployed        SQL;Python;TypeScript;HTML/CSS;Dart;JavaScript       0.0
                  Swift                                            58660.0
                  Swift;TypeScript;PHP                             33960.0
                  TypeScript;Bash/Shell;Swift;Elixir;C#            32460.0
                  TypeScript;JavaScript;Bash/Shell                     0.0

[1709 rows x 8 columns]

In [20]:
us_df.groupby(['employment_status','languages_used'])['annual_salary_usd'].nlargest(10)

employment_status  languages_used
Freelance          Bash/Shell;Python;Java                          7914    147700
                   C#;Java;Python;Swift                            7307    101000
                   C#;PHP;Python;TypeScript;Swift                  6113    137000
                   C#;PHP;SQL;Python;Go                            2953     88700
                   C;Python                                        4029     17500
                                                                            ...
Unemployed         Python;JavaScript;SQL;TypeScript;Java;Elixir    3607     13220
                   Python;Kotlin                                   2926      3260
                   Python;TypeScript;C#;Java;SQL;C++               5664     31200
                   Rust;JavaScript;Python;C;C++;HTML/CSS           3933     23380
                   SQL;Python;TypeScript;HTML/CSS;Dart;JavaScript  9997         0
Name: annual_salary_usd, Length: 754, dtype: int64

In [21]:
us_df.columns

Index(['country', 'employment_status', 'languages_used', 'annual_salary_usd'], dtype='object')

In [22]:
us_df.head(100)

,country,employment_status,languages_used,annual_salary_usd
11,United States,Full-time,SQL;Go;Python;JavaScript,211500
40,United States,Full-time,Python;Dart;Go;HTML/CSS,37200
49,United States,Student,Python;JavaScript;C#;HTML/CSS;Swift,19840
108,United States,Part-time,Bash/Shell;Python;C#;Go;Rust;Kotlin,221900
109,United States,Unemployed,Elixir;JavaScript;Python,0
...,...,...,...,...
1680,United States,Full-time,Go;SQL;Python;C#;Bash/Shell;Kotlin,86000
1687,United States,Full-time,JavaScript;TypeScript;Python;HTML/CSS,187800
1693,United States,Full-time,SQL;TypeScript;C#;HTML/CSS;Python;JavaScript,90700
1694,United States,Full-time,C;SQL;JavaScript;Python;C#,181600
1695,United States,Full-time,Java;C++;Python,77400

In [23]:
us_df.reset_index()

,index,country,employment_status,languages_used,annual_salary_usd
0,11,United States,Full-time,SQL;Go;Python;JavaScript,211500
1,40,United States,Full-time,Python;Dart;Go;HTML/CSS,37200
2,49,United States,Student,Python;JavaScript;C#;HTML/CSS;Swift,19840
3,108,United States,Part-time,Bash/Shell;Python;C#;Go;Rust;Kotlin,221900
4,109,United States,Unemployed,Elixir;JavaScript;Python,0
...,...,...,...,...,...
778,11930,United States,Part-time,C;SQL;Python;C++;Java;HTML/CSS,110200
779,11939,United States,Full-time,Swift;Python;Zig,23600
780,11962,United States,Full-time,Python;Bash/Shell;HTML/CSS,46400
781,11970,United States,Full-time,Python;TypeScript;JavaScript;Go,158900
782,11984,United States,Full-time,JavaScript;SQL;Python,155700

In [24]:
df.head(10)

,respondent_id,survey_year,country,age,gender,education_level,years_of_experience,role,employment_status,company_size,...,ai_usage_frequency,ai_productivity_boost_pct,ai_sentiment,ai_job_threat_perception,primary_learning_source,open_source_contributor,looking_for_job,remote_work_preference_1to5,burnout_frequency,want_to_learn_next
0,R00001,2024,India,43,Man,Some college,22,Front-End Developer,Unemployed,1-10,...,Weekly,14,Somewhat positive,Minimal threat,Online courses,1,Actively looking,2,Sometimes,Elixir;Zig;AI/ML
1,R00002,2025,Italy,28,Man,Master's degree,7,Machine Learning Engineer,Unemployed,201-1000,...,Weekly,8,Somewhat positive,Minimal threat,Stack Overflow,1,Not looking,4,Often,Kubernetes;Elixir;Go
2,R00003,2021,South Africa,23,Woman,Master's degree,0,Machine Learning Engineer,Full-time,1001-5000,...,Rarely,1,Very negative,Significant threat,YouTube,0,Open to offers,5,Often,Go
3,R00004,2023,India,22,Prefer not to say,Bachelor's degree,1,QA / Test Engineer,Unemployed,10000+,...,Multiple times daily,61,Neutral,Minimal threat,Stack Overflow,1,Open to offers,3,Rarely,HTMX;Swift;Rust
4,R00005,2025,United States,34,Man,Bachelor's degree,11,Front-End Developer,Full-time,51-200,...,Weekly,15,Neutral,Moderate threat,Official docs,0,Open to offers,1,Sometimes,TypeScript
5,R00006,2021,India,33,Man,Bachelor's degree,15,Front-End Developer,Full-time,51-200,...,Daily,36,Very positive,Significant threat,Stack Overflow,0,Not looking,3,Sometimes,Kubernetes;TypeScript
6,R00007,2022,China,29,Man,Bachelor's degree,13,Cloud Engineer,Full-time,1001-5000,...,Monthly,8,Somewhat positive,Minimal threat,Official docs,0,Not looking,5,Often,AI/ML;Go
7,R00008,2022,India,31,Man,Bachelor's degree,12,Full-Stack Developer,Full-time,51-200,...,Multiple times daily,16,Neutral,No threat,Books,1,Not looking,5,Often,Kotlin;Swift;Kubernetes
8,R00009,2025,United States,46,Man,Bachelor's degree,26,Front-End Developer,Full-time,201-1000,...,Weekly,26,Somewhat positive,Will replace most devs,YouTube,0,Not looking,5,Often,Swift;HTMX
9,R00010,2020,Indonesia,37,Man,Self-taught / Bootcamp,11,Front-End Developer,Full-time,1001-5000,...,Weekly,19,Very negative,Significant threat,ChatGPT/AI,1,Actively looking,4,Rarely,Rust;Kotlin;Go