In [42]:
import pandas as pd
import sqlite3

In [12]:
filename='developer.csv'

In [15]:
df = pd.read_csv(filename, index_col='respondent_id')

In [16]:
df.head()

,survey_year,country,age,gender,education_level,years_of_experience,role,employment_status,company_size,work_mode,...,ai_usage_frequency,ai_productivity_boost_pct,ai_sentiment,ai_job_threat_perception,primary_learning_source,open_source_contributor,looking_for_job,remote_work_preference_1to5,burnout_frequency,want_to_learn_next
respondent_id,,,,,,,,,,,,,,,,,,,,,
R00001,2024,India,43,Man,Some college,22,Front-End Developer,Unemployed,1-10,Hybrid,...,Weekly,14,Somewhat positive,Minimal threat,Online courses,1,Actively looking,2,Sometimes,Elixir;Zig;AI/ML
R00002,2025,Italy,28,Man,Master's degree,7,Machine Learning Engineer,Unemployed,201-1000,Remote,...,Weekly,8,Somewhat positive,Minimal threat,Stack Overflow,1,Not looking,4,Often,Kubernetes;Elixir;Go
R00003,2021,South Africa,23,Woman,Master's degree,0,Machine Learning Engineer,Full-time,1001-5000,In-Office,...,Rarely,1,Very negative,Significant threat,YouTube,0,Open to offers,5,Often,Go
R00004,2023,India,22,Prefer not to say,Bachelor's degree,1,QA / Test Engineer,Unemployed,10000+,Hybrid,...,Multiple times daily,61,Neutral,Minimal threat,Stack Overflow,1,Open to offers,3,Rarely,HTMX;Swift;Rust
R00005,2025,United States,34,Man,Bachelor's degree,11,Front-End Developer,Full-time,51-200,Remote,...,Weekly,15,Neutral,Moderate threat,Official docs,0,Open to offers,1,Sometimes,TypeScript

In [26]:
filt= df['country']=='India'

In [25]:
df.loc['R00001']['country']

'India'

In [28]:
india_df=df.loc[filt]

In [29]:
india_df.head()

,survey_year,country,age,gender,education_level,years_of_experience,role,employment_status,company_size,work_mode,...,ai_usage_frequency,ai_productivity_boost_pct,ai_sentiment,ai_job_threat_perception,primary_learning_source,open_source_contributor,looking_for_job,remote_work_preference_1to5,burnout_frequency,want_to_learn_next
respondent_id,,,,,,,,,,,,,,,,,,,,,
R00001,2024,India,43,Man,Some college,22,Front-End Developer,Unemployed,1-10,Hybrid,...,Weekly,14,Somewhat positive,Minimal threat,Online courses,1,Actively looking,2,Sometimes,Elixir;Zig;AI/ML
R00004,2023,India,22,Prefer not to say,Bachelor's degree,1,QA / Test Engineer,Unemployed,10000+,Hybrid,...,Multiple times daily,61,Neutral,Minimal threat,Stack Overflow,1,Open to offers,3,Rarely,HTMX;Swift;Rust
R00006,2021,India,33,Man,Bachelor's degree,15,Front-End Developer,Full-time,51-200,In-Office,...,Daily,36,Very positive,Significant threat,Stack Overflow,0,Not looking,3,Sometimes,Kubernetes;TypeScript
R00008,2022,India,31,Man,Bachelor's degree,12,Full-Stack Developer,Full-time,51-200,Remote,...,Multiple times daily,16,Neutral,No threat,Books,1,Not looking,5,Often,Kotlin;Swift;Kubernetes
R00015,2021,India,21,Man,Master's degree,2,Student / Intern,Full-time,201-1000,Hybrid,...,Multiple times daily,45,Very positive,Minimal threat,Official docs,0,Open to offers,4,Often,Python;HTMX

In [30]:
india_df.to_csv('modfied.csv')

In [31]:
india_df.to_csv('modfied.tsv', sep='\t')  #tab separated file

In [33]:
india_df.to_excel('modified.xlsx')

In [35]:
test = pd.read_excel('modified.xlsx',index_col='respondent_id')

In [36]:
test.head()

,survey_year,country,age,gender,education_level,years_of_experience,role,employment_status,company_size,work_mode,...,ai_usage_frequency,ai_productivity_boost_pct,ai_sentiment,ai_job_threat_perception,primary_learning_source,open_source_contributor,looking_for_job,remote_work_preference_1to5,burnout_frequency,want_to_learn_next
respondent_id,,,,,,,,,,,,,,,,,,,,,
R00001,2024,India,43,Man,Some college,22,Front-End Developer,Unemployed,1-10,Hybrid,...,Weekly,14,Somewhat positive,Minimal threat,Online courses,1,Actively looking,2,Sometimes,Elixir;Zig;AI/ML
R00004,2023,India,22,Prefer not to say,Bachelor's degree,1,QA / Test Engineer,Unemployed,10000+,Hybrid,...,Multiple times daily,61,Neutral,Minimal threat,Stack Overflow,1,Open to offers,3,Rarely,HTMX;Swift;Rust
R00006,2021,India,33,Man,Bachelor's degree,15,Front-End Developer,Full-time,51-200,In-Office,...,Daily,36,Very positive,Significant threat,Stack Overflow,0,Not looking,3,Sometimes,Kubernetes;TypeScript
R00008,2022,India,31,Man,Bachelor's degree,12,Full-Stack Developer,Full-time,51-200,Remote,...,Multiple times daily,16,Neutral,No threat,Books,1,Not looking,5,Often,Kotlin;Swift;Kubernetes
R00015,2021,India,21,Man,Master's degree,2,Student / Intern,Full-time,201-1000,Hybrid,...,Multiple times daily,45,Very positive,Minimal threat,Official docs,0,Open to offers,4,Often,Python;HTMX

In [38]:
india_df.to_json('modified.json',orient='records',lines=True)

In [39]:
test = pd.read_json('modified.json',orient='records',lines=True)

In [41]:
test.head()

,survey_year,country,age,gender,education_level,years_of_experience,role,employment_status,company_size,work_mode,...,ai_usage_frequency,ai_productivity_boost_pct,ai_sentiment,ai_job_threat_perception,primary_learning_source,open_source_contributor,looking_for_job,remote_work_preference_1to5,burnout_frequency,want_to_learn_next
0,2024,India,43,Man,Some college,22,Front-End Developer,Unemployed,1-10,Hybrid,...,Weekly,14,Somewhat positive,Minimal threat,Online courses,1,Actively looking,2,Sometimes,Elixir;Zig;AI/ML
1,2023,India,22,Prefer not to say,Bachelor's degree,1,QA / Test Engineer,Unemployed,10000+,Hybrid,...,Multiple times daily,61,Neutral,Minimal threat,Stack Overflow,1,Open to offers,3,Rarely,HTMX;Swift;Rust
2,2021,India,33,Man,Bachelor's degree,15,Front-End Developer,Full-time,51-200,In-Office,...,Daily,36,Very positive,Significant threat,Stack Overflow,0,Not looking,3,Sometimes,Kubernetes;TypeScript
3,2022,India,31,Man,Bachelor's degree,12,Full-Stack Developer,Full-time,51-200,Remote,...,Multiple times daily,16,Neutral,No threat,Books,1,Not looking,5,Often,Kotlin;Swift;Kubernetes
4,2021,India,21,Man,Master's degree,2,Student / Intern,Full-time,201-1000,Hybrid,...,Multiple times daily,45,Very positive,Minimal threat,Official docs,0,Open to offers,4,Often,Python;HTMX

In [43]:
from sqlalchemy  import create_engine

In [45]:
engine = create_engine('sqlite:///myNorthwind.db')

In [50]:
# Read an entire table without typing custom SQL
df_customers= pd.read_sql_table("customers", con=engine, index_col='CustomerID')

In [51]:
df_customers.head()

,CompanyName,ContacttName,ContactTitle,Address,City,Country
CustomerID,,,,,,
1151,"Asper, Inc",Peter Mitchell,Sales,1212 Main St,Dallas,USA
116,Microsoft,Peter Window,Technical,None,San Diego,None
117,Michigan Mfg,Marty Mich,manager,343 Main St,Detroit,USA
ALFKI,Alfreds Futterkiste,Maria Anders,Sales Representative,Obere Str. 57,Berlin,Germany
ANATR,Ana Trujillo Emparedados y helados,Ana Trujillo,Owner,Avda. de la Constitución 2222,México D.F.,Mexico

In [49]:
india_df.to_sql('sample_table',engine)

1686

In [56]:
customer_df=pd.read_sql_query('SELECT * From Customers WHERE country="USA" ',engine, index_col='CustomerID')

In [57]:
customer_df.head()

,CompanyName,ContacttName,ContactTitle,Address,City,Country
CustomerID,,,,,,
1151,"Asper, Inc",Peter Mitchell,Sales,1212 Main St,Dallas,USA
117,Michigan Mfg,Marty Mich,manager,343 Main St,Detroit,USA
GREAL,Great Lakes Food Market,Howard Snyder,Marketing Manager,2732 Baker Blvd.,Eugene,USA
HUNGC,Hungry Coyote Import Store,Yoshi Latimer,Sales Representative,City Center Plaza 516 Main St.,Elgin,USA
joma,JoeMain,Joe Main,None,123 NewMain,Dallas,USA

In [69]:
df_customers.reset_index()

,CustomerID,CompanyName,ContacttName,ContactTitle,Address,City,Country
0,1151,"Asper, Inc",Peter Mitchell,Sales,1212 Main St,Dallas,USA
1,116,Microsoft,Peter Window,Technical,None,San Diego,None
2,117,Michigan Mfg,Marty Mich,manager,343 Main St,Detroit,USA
3,ALFKI,Alfreds Futterkiste,Maria Anders,Sales Representative,Obere Str. 57,Berlin,Germany
4,ANATR,Ana Trujillo Emparedados y helados,Ana Trujillo,Owner,Avda. de la Constitución 2222,México D.F.,Mexico
...,...,...,...,...,...,...,...
91,WARTH,Wartian Herkku,Pirkko Koskitalo,Accounting Manager,Torikatu 38,Oulu,Finland
92,WELLI,Wellington Importadora,Paula Parente,Sales Manager,"Rua do Mercado, 12",Resende,Brazil
93,WHITC,White Clover Markets,Karl Jablonski,Owner,305 - 14th Ave. S. Suite 3B,Seattle,USA
94,WILMK,Wilman Kala,Matti Karttunen,Owner/Marketing Assistant,Keskuskatu 45,Helsinki,Finland
95,WOLZA,Wolski Zajazd,Zbyszek Piestrzeniewicz,Owner,ul. Filtrowa 68,Warszawa,Poland

In [71]:
df_names=df_customers.groupby('Country')[['Country','CompanyName']]

In [72]:
df_names.head(10)

            Country                         CompanyName
CustomerID
1151            USA                          Asper, Inc
117             USA                        Michigan Mfg
ALFKI       Germany                 Alfreds Futterkiste
ANATR        Mexico  Ana Trujillo Emparedados y helados
ANTON        Mexico             Antonio Moreno Taquería
...             ...                                 ...
VICTE        France                Victuailles en stock
WARTH       Finland                      Wartian Herkku
WELLI        Brazil              Wellington Importadora
WILMK       Finland                         Wilman Kala
WOLZA        Poland                      Wolski  Zajazd

[86 rows x 2 columns]