In [1]:
import numpy as  np

In [2]:
import pandas as pd

In [3]:
import seaborn as sns

In [4]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [5]:
df=sns.load_dataset('tips')

In [6]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [7]:
#normal groupby

In [15]:
df.groupby('time',observed=False)['total_bill'].mean()

time
Lunch     17.168676
Dinner    20.797159
Name: total_bill, dtype: float64

In [9]:
# to_frame

In [17]:
df.groupby('time',observed=False)['total_bill'].mean().to_frame('avg_bill')

         avg_bill
time
Lunch   17.168676
Dinner  20.797159

In [19]:
df.groupby('time',observed=False)['total_bill'].mean().to_frame('avg_bill')

         avg_bill
time
Lunch   17.168676
Dinner  20.797159

In [20]:
df.groupby('time',observed=False)['total_bill'].mean().to_frame('avg_bill').reset_index()

     time   avg_bill
0   Lunch  17.168676
1  Dinner  20.797159

In [25]:
df.groupby('time',observed=False)['total_bill'].mean().to_frame('avg_bill').reset_index().sort_values('avg_bill',ascending=False)

     time   avg_bill
1  Dinner  20.797159
0   Lunch  17.168676

In [ ]:
#assign to a new dataframe

In [26]:
avg_bill=df.groupby('time',observed=False)['total_bill'].mean().to_frame('avg_bill').reset_index().sort_values('avg_bill',ascending=False)

In [27]:
avg_bill

     time   avg_bill
1  Dinner  20.797159
0   Lunch  17.168676

In [ ]:
#common Calculations .sum(), .count() / .min() / .Max() / .mean()

In [28]:
df.groupby('time',observed=False)['total_bill'].count()

time
Lunch      68
Dinner    176
Name: total_bill, dtype: int64

In [29]:
df.groupby('time',observed=False)['total_bill'].size()

time
Lunch      68
Dinner    176
Name: total_bill, dtype: int64

In [30]:
df.groupby('time',observed=False)['total_bill'].nunique()

time
Lunch      64
Dinner    168
Name: total_bill, dtype: int64

In [31]:
df.groupby('time',observed=False)['total_bill'].max()

time
Lunch     43.11
Dinner    50.81
Name: total_bill, dtype: float64

In [32]:
df.groupby('time',observed=False)['total_bill'].min()

time
Lunch     7.51
Dinner    3.07
Name: total_bill, dtype: float64

In [33]:
df.groupby('time',observed=False)['total_bill'].sum()

time
Lunch     1167.47
Dinner    3660.30
Name: total_bill, dtype: float64

In [ ]:
#numpy also allowed

In [34]:
df.groupby('time',observed=False)['total_bill'].median()

time
Lunch     15.965
Dinner    18.390
Name: total_bill, dtype: float64

In [ ]:
#question 1 find  the  average tip for each night  of the  week

In [36]:
df.groupby('day',observed=False)['tip'].mean()

day
Thur    2.771452
Fri     2.734737
Sat     2.993103
Sun     3.255132
Name: tip, dtype: float64

In [ ]:
#question find  the  average tip for  each sex

In [37]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [38]:
df.groupby('sex',observed='False')['tip'].max()

sex
Male      10.0
Female     6.5
Name: tip, dtype: float64

In [ ]:
#question 3  quantile --> top 10% for tips each  night

In [41]:
df.groupby('day',observed=False)['tip'].quantile(.9)

day
Thur    4.920
Fri     4.060
Sat     4.802
Sun     5.035
Name: tip, dtype: float64

In [ ]:
# multiple calculations .agg() + formats

In [44]:
df.groupby('time',observed=False)['total_bill'].agg(['min','max'])

         min    max
time
Lunch   7.51  43.11
Dinner  3.07  50.81

In [48]:
df.groupby('time',observed=False)['total_bill'].agg(['min','median','max'])

         min  median    max
time
Lunch   7.51  15.965  43.11
Dinner  3.07  18.390  50.81

In [52]:
df.groupby('time',observed=False)['total_bill'].agg(minimum='min',median='median',maximum='max')

        minimum  median  maximum
time
Lunch      7.51  15.965    43.11
Dinner     3.07  18.390    50.81

In [53]:
df.groupby('time',observed=False)['total_bill'].agg(['min','median','max']).rename(columns={'min':'minimum','max':'maximum'})

        minimum  median  maximum
time
Lunch      7.51  15.965    43.11
Dinner     3.07  18.390    50.81

In [ ]:
# .describe

In [54]:
df.groupby('time',observed=False)['total_bill'].describe()

        count       mean       std   min      25%     50%      75%    max
time
Lunch    68.0  17.168676  7.713882  7.51  12.2350  15.965  19.5325  43.11
Dinner  176.0  20.797159  9.142029  3.07  14.4375  18.390  25.2825  50.81

In [ ]:
# two calc columns

In [55]:
df.groupby('time',observed=False)[['total_bill','tip']].mean()

        total_bill       tip
time
Lunch    17.168676  2.728088
Dinner   20.797159  3.102670

In [ ]:
# 2 groupby columns

In [56]:
df.groupby(['time','day'],observed=False)['total_bill'].mean()

time    day
Lunch   Thur    17.664754
        Fri     12.845714
        Sat           NaN
        Sun           NaN
Dinner  Thur    18.780000
        Fri     19.663333
        Sat     20.441379
        Sun     21.410000
Name: total_bill, dtype: float64

In [57]:
df.groupby(['day','time'],observed=False)['total_bill'].mean()

day   time
Thur  Lunch     17.664754
      Dinner    18.780000
Fri   Lunch     12.845714
      Dinner    19.663333
Sat   Lunch           NaN
      Dinner    20.441379
Sun   Lunch           NaN
      Dinner    21.410000
Name: total_bill, dtype: float64

In [58]:
df.groupby(['time','day'],observed=False)[['tip','total_bill']].mean()

                  tip  total_bill
time   day
Lunch  Thur  2.767705   17.664754
       Fri   2.382857   12.845714
       Sat        NaN         NaN
       Sun        NaN         NaN
Dinner Thur  3.000000   18.780000
       Fri   2.940000   19.663333
       Sat   2.993103   20.441379
       Sun   3.255132   21.410000

In [59]:
df.groupby(['time','day'],observed=False)[['tip','total_bill']].mean().reset_index()

     time   day       tip  total_bill
0   Lunch  Thur  2.767705   17.664754
1   Lunch   Fri  2.382857   12.845714
2   Lunch   Sat       NaN         NaN
3   Lunch   Sun       NaN         NaN
4  Dinner  Thur  3.000000   18.780000
5  Dinner   Fri  2.940000   19.663333
6  Dinner   Sat  2.993103   20.441379
7  Dinner   Sun  3.255132   21.410000

In [ ]:
# 2 fillna to handle  Nan but in the  video he uses 
#df.groupby(['time', 'day'], observed=False)[['tip', 'total_bill']].mean().reset_index().fillna(0)
#this gives an error. the fix is:
#df.groupby(['time', 'day'], observed=False)[['tip', 'total_bill']].mean().reset_index().astype({'time': 'str', 'day': 'str'}).fillna(0)

In [61]:
df.groupby(['time', 'day'], observed=False)[['tip', 'total_bill']].mean().reset_index().astype({'time': 'str', 'day': 'str'}).fillna(0)

     time   day       tip  total_bill
0   Lunch  Thur  2.767705   17.664754
1   Lunch   Fri  2.382857   12.845714
2   Lunch   Sat  0.000000    0.000000
3   Lunch   Sun  0.000000    0.000000
4  Dinner  Thur  3.000000   18.780000
5  Dinner   Fri  2.940000   19.663333
6  Dinner   Sat  2.993103   20.441379
7  Dinner   Sun  3.255132   21.410000

In [ ]:
# transform

In [63]:
dftransform=sns.load_dataset('tips')

In [65]:
dftransform

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

dftransform['medianbill']= dftransform.groupby('time')['total_bill'].transform('median')

In [98]:
dftransform['medianbill'] = dftransform.groupby('time',observed =False)['total_bill'].transform('median')

In [78]:
dftransform

     total_bill   tip     sex smoker   day    time  size  medianbill
0         16.99  1.01  Female     No   Sun  Dinner     2       18.39
1         10.34  1.66    Male     No   Sun  Dinner     3       18.39
2         21.01  3.50    Male     No   Sun  Dinner     3       18.39
3         23.68  3.31    Male     No   Sun  Dinner     2       18.39
4         24.59  3.61  Female     No   Sun  Dinner     4       18.39
..          ...   ...     ...    ...   ...     ...   ...         ...
239       29.03  5.92    Male     No   Sat  Dinner     3       18.39
240       27.18  2.00  Female    Yes   Sat  Dinner     2       18.39
241       22.67  2.00    Male    Yes   Sat  Dinner     2       18.39
242       17.82  1.75    Male     No   Sat  Dinner     2       18.39
243       18.78  3.00  Female     No  Thur  Dinner     2       18.39

[244 rows x 8 columns]

In [80]:
dftransform.query('time=="Lunch"')

     total_bill   tip     sex smoker   day   time  size  medianbill
77        27.20  4.00    Male     No  Thur  Lunch     4      15.965
78        22.76  3.00    Male     No  Thur  Lunch     2      15.965
79        17.29  2.71    Male     No  Thur  Lunch     2      15.965
80        19.44  3.00    Male    Yes  Thur  Lunch     2      15.965
81        16.66  3.40    Male     No  Thur  Lunch     2      15.965
..          ...   ...     ...    ...   ...    ...   ...         ...
222        8.58  1.92    Male    Yes   Fri  Lunch     1      15.965
223       15.98  3.00  Female     No   Fri  Lunch     3      15.965
224       13.42  1.58    Male    Yes   Fri  Lunch     2      15.965
225       16.27  2.50  Female    Yes   Fri  Lunch     2      15.965
226       10.09  2.00  Female    Yes   Fri  Lunch     2      15.965

[68 rows x 8 columns]

In [81]:
dftransform.query('time=="Dinner"')

     total_bill   tip     sex smoker   day    time  size  medianbill
0         16.99  1.01  Female     No   Sun  Dinner     2       18.39
1         10.34  1.66    Male     No   Sun  Dinner     3       18.39
2         21.01  3.50    Male     No   Sun  Dinner     3       18.39
3         23.68  3.31    Male     No   Sun  Dinner     2       18.39
4         24.59  3.61  Female     No   Sun  Dinner     4       18.39
..          ...   ...     ...    ...   ...     ...   ...         ...
239       29.03  5.92    Male     No   Sat  Dinner     3       18.39
240       27.18  2.00  Female    Yes   Sat  Dinner     2       18.39
241       22.67  2.00    Male    Yes   Sat  Dinner     2       18.39
242       17.82  1.75    Male     No   Sat  Dinner     2       18.39
243       18.78  3.00  Female     No  Thur  Dinner     2       18.39

[176 rows x 8 columns]

In [82]:
dftransform.query('total_bill > medianbill')

     total_bill   tip     sex smoker   day    time  size  medianbill
2         21.01  3.50    Male     No   Sun  Dinner     3       18.39
3         23.68  3.31    Male     No   Sun  Dinner     2       18.39
4         24.59  3.61  Female     No   Sun  Dinner     4       18.39
5         25.29  4.71    Male     No   Sun  Dinner     4       18.39
7         26.88  3.12    Male     No   Sun  Dinner     4       18.39
..          ...   ...     ...    ...   ...     ...   ...         ...
238       35.83  4.67  Female     No   Sat  Dinner     3       18.39
239       29.03  5.92    Male     No   Sat  Dinner     3       18.39
240       27.18  2.00  Female    Yes   Sat  Dinner     2       18.39
241       22.67  2.00    Male    Yes   Sat  Dinner     2       18.39
243       18.78  3.00  Female     No  Thur  Dinner     2       18.39

[122 rows x 8 columns]

In [84]:
# show a  lambda Example  -> z-score for each group. where data lies  on  normal distribution curve

In [99]:
dftransform['zscore'] = dftransform.groupby('time',observed = False)['total_bill'].transform(lambda x : (x-x.mean())/x.std())

In [100]:
dftransform

     total_bill   tip     sex smoker   day    time  size  medianbill    zscore
0         16.99  1.01  Female     No   Sun  Dinner     2       18.39 -0.416446
1         10.34  1.66    Male     No   Sun  Dinner     3       18.39 -1.143855
2         21.01  3.50    Male     No   Sun  Dinner     3       18.39  0.023282
3         23.68  3.31    Male     No   Sun  Dinner     2       18.39  0.315339
4         24.59  3.61  Female     No   Sun  Dinner     4       18.39  0.414880
..          ...   ...     ...    ...   ...     ...   ...         ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3       18.39  0.900549
240       27.18  2.00  Female    Yes   Sat  Dinner     2       18.39  0.698186
241       22.67  2.00    Male    Yes   Sat  Dinner     2       18.39  0.204861
242       17.82  1.75    Male     No   Sat  Dinner     2       18.39 -0.325656
243       18.78  3.00  Female     No  Thur  Dinner     2       18.39 -0.220647

[244 rows x 9 columns]

In [101]:
# apply for lambda

In [107]:
dftransform.groupby('time',observed=False).apply(lambda x : (x['tip']/x['total_bill']).mean(),include_groups=False).to_frame('avgtipPercent').reset_index()

     time  avgtipPercent
0   Lunch       0.164128
1  Dinner       0.159518

In [108]:
dftransform.groupby('time',observed=False).apply(lambda x : ((x['tip']/x['total_bill'])*100).mean(),include_groups=False).to_frame('avgtipPercent').reset_index()

     time  avgtipPercent
0   Lunch      16.412793
1  Dinner      15.951779

In [109]:
#function within a groupby

In [113]:
tx = sns.load_dataset('taxis')

In [116]:
tx

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [117]:
tx['pickup'].dt.month

0       3
1       3
2       3
3       3
4       3
       ..
6428    3
6429    3
6430    3
6431    3
6432    3
Name: pickup, Length: 6433, dtype: int32

In [118]:
tx.groupby(tx['pickup'].dt.month)['distance'].mean()

pickup
2    0.900000
3    3.024947
Name: distance, dtype: float64

In [ ]:
#question1 -> Interquartile Range  Q3-Q1 for tips  with boroughs ->apply

In [124]:
tx.columns

Index(['pickup', 'dropoff', 'passengers', 'distance', 'fare', 'tip', 'tolls',
       'total', 'color', 'payment', 'pickup_zone', 'dropoff_zone',
       'pickup_borough', 'dropoff_borough'],
      dtype='object')

In [139]:
tx.groupby('pickup_borough').apply(lambda x :  x['tip'].quantile(.75)-x['tip'].quantile(.25),include_groups=False)

pickup_borough
Bronx        0.000
Brooklyn     1.655
Manhattan    2.800
Queens       5.950
dtype: float64

In [ ]:
#question2 -> Show Mean, MIN,MAX_FARE for payment type and  taxi_color 
#relabel Mean  as avg, min  as minimum, MAX as Maximum

In [135]:
tx.groupby(['payment','color'])['fare'].agg(avg='mean',minimun='min',maximum='max')

                          avg  minimun  maximum
payment     color
cash        green    9.987500      2.5    150.0
            yellow  12.047805      1.0    150.0
credit card green   16.938735      2.5     93.5
            yellow  13.226805      2.5    120.0

In [120]:
#question3a-> Output the avg total  for taxi color total for each row

In [129]:
tx['avgtotal']=tx.groupby('color')['total'].transform('mean')

In [130]:
tx

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough,avgtotal
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan,18.884252
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan,18.884252
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan,18.884252
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan,18.884252
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan,18.884252
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan,16.483615
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx,16.483615
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn,16.483615
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn,16.483615
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn,16.483615

In [121]:
#question3b -> Output the rows that have a total greater  than the avg color

In [132]:
tx.query('total>avgtotal')

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough,avgtotal
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.00,6.15,0.00,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan,18.884252
8,2019-03-23 11:48:50,2019-03-23 12:06:14,1,3.63,15.00,1.00,0.00,19.30,yellow,credit card,East Harlem South,Midtown Center,Manhattan,Manhattan,18.884252
22,2019-03-28 17:20:54,2019-03-28 17:55:57,1,9.82,31.50,8.31,5.76,49.87,yellow,credit card,LaGuardia Airport,Sutton Place/Turtle Bay North,Queens,Manhattan,18.884252
27,2019-03-16 20:30:36,2019-03-16 20:46:22,1,2.60,12.50,3.26,0.00,19.56,yellow,credit card,Clinton East,Lenox Hill West,Manhattan,Manhattan,18.884252
35,2019-03-01 17:39:58,2019-03-01 18:04:46,1,3.06,17.00,4.26,0.00,25.56,yellow,credit card,West Chelsea/Hudson Yards,Lenox Hill East,Manhattan,Manhattan,18.884252
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6425,2019-03-07 15:34:30,2019-03-07 16:31:06,1,9.12,26.32,0.00,0.00,26.82,green,credit card,Park Slope,East New York,Brooklyn,Brooklyn,16.483615
6427,2019-03-23 18:26:09,2019-03-23 18:49:12,1,7.07,20.00,0.00,0.00,20.00,green,cash,Parkchester,East Harlem South,Bronx,Manhattan,16.483615
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.00,0.00,0.00,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx,16.483615
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.00,0.00,0.00,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn,16.483615
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.00,3.36,0.00,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn,16.483615